<div id="main-panel" class="bb fantasy">
<?php
if (!empty($this->message)) {
    ?>
    <h2><?php echo $this->message; ?></h2>
    <?php
} else {
    echo $this->partial('render/list-data.phtml', array(
                        'object'       => $this->people,
                        'title'        => $this->translate->_('People'),
                        'personOrPage' => 'person',
                        'translate'    => $this->translate
        ));

    echo $this->partial('render/list-data.phtml', array(
                'object'       => $this->pages,
                'title'        => $this->translate->_('Pages'),
                'personOrPage' => 'page',
                'translate'    => $this->translate
    ));
}
?>
</div>
<?php
