<div id="main-panel" class="bb fantasy">
    <div class="main-background-color one-personal-settings-section">
        <div class="favourite-page-container m-t-10 current-favourite-pages">
            <h3 class="text-align-center m-b-10"><?php echo $this->translate->_('Current favorites'); ?></h3>
            <table class="table">
                <tr>
                    <th><?php echo $this->translate->_('Page Name'); ?></th>
                    <th><?php echo $this->translate->_('Widget Settings'); ?></th>
                    <th><?php echo $this->translate->_('Unlike'); ?></th>
                    <th><?php echo $this->translate->_('Show in favorite pages widget?'); ?></th>
                </tr>
                <?php
                foreach ($this->favoritePages as $onePage) {
                    ?>
                    <tr>
                        <td>
                            <a href="<?php echo APP_URL; ?>/page/index/pageID/<?php echo $onePage['id']; ?>">
                                <?php echo $onePage['title']; ?>
                            </a>
                        </td>
                        <td>
                            <a data-url="/widget/configure-widget-for-user/pageID/<?php echo $onePage['id']; ?>" class="blue-button modal-open" href="javascript:void(0)">
                                <i class="fa fa-cog"></i>
                            </a>
                        </td>
                        <td>
                            <a class="blue-button unfavorite-page" data-id="<?php echo $onePage['id']; ?>" href="javascript:void(0)">
                                <i class="fa fa-heartbeat"></i>
                            </a>
                        </td>
                        <td>
                            <?php $checked = $onePage['show_in_favorite_pages_widget'] ? 'checked="checked"' : ''; ?>
                            <input <?php echo $checked; ?> class="show-in-widget-favorite cursor-pointer" data-id="<?php echo $onePage['id']; ?>" type="checkbox">
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </div>
        <div class="favourite-page-container m-t-10 m-l-20 ex-favourite-pages">
            <h3 class="text-align-center m-b-10"><?php echo $this->translate->_('Ex-favorites'); ?></h3>
            <table class="table">
                <tr>
                    <th><?php echo $this->translate->_('Page Name'); ?></th>
                    <th><?php echo $this->translate->_('Like'); ?></th>
                </tr>
                <?php
                foreach ($this->exFavoritePages as $onePage) {
                ?>
                <tr>
                    <td><a href="<?php echo APP_URL; ?>/page/index/pageID/<?php echo $onePage['id']; ?>"><?php echo $onePage['title'] ;?></td>
                    <td><a data-id="<?php echo $onePage['id']; ?>" class="blue-button favourite-page-back" href="javascript:void(0)"><i class="fa fa-heart"></i></a></td>
                </tr>
                <?php
                }
                ?>
            </table>
        </div>
    </div>
    <div class="main-background-color one-personal-settings-section">
        <h2 class="widget-header-color display-inline-block"><?php echo $this->translate->_('Favorite posts'); ?></h2>
        <div class="display-inline-block add-dream-team-container">
            <select class="width-200px add-dream-team-sport">
                <option value="11"><?php echo $this->translate->_('Date (ascending)'); ?></option>
                <option value="5"><?php echo $this->translate->_('Date (descending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Post Author First Name (ascending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Post Author First Name (descending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Post Author Last Name (ascending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Post Author Last Name (descending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Title (ascending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Title (descending)'); ?></option>
            </select>
            <input type="text" class="search-favourite-content" placeholder="<?php echo $this->translate->_('Search post content, title or author'); ?>">
            <a class="blue-button" href="javascript:void(0)"><?php echo $this->translate->_('Search'); ?></a>
        </div>
        <div class="clear"></div>
        <div class="p-10">
        <?php
        foreach ($this->postFavorites as $onePost) {
        ?>
            <div class="display-inline-block width-200px favorite-post-container">
                <p class="truncate-string"><?php echo $onePost['post_text']; ?></p>
            </div>
        <?php
        }
        ?>
        </div>
    </div>
    <div class="main-background-color one-personal-settings-section">
        <h2 class="widget-header-color display-inline-block"><?php echo $this->translate->_('Favorite comments'); ?></h2>
        <div class="display-inline-block add-dream-team-container">
            <select class="width-200px add-dream-team-sport">
                <option value="11"><?php echo $this->translate->_('Date (ascending)'); ?></option>
                <option value="5"><?php echo $this->translate->_('Date (descending)'); ?></option>
                <option value="7"><?php echo $this->translate->_('Text'); ?></option>
            </select>
            <input type="text" class="search-favourite-content" placeholder="<?php echo $this->translate->_('Search post content, title or author'); ?>">
            <a class="blue-button" href="javascript:void(0)"><?php echo $this->translate->_('Search'); ?></a>
        </div>
        <div class="clear"></div>
        <div class="p-10">
        <?php
        foreach ($this->commentFavorites as $oneComment) {
        ?>
            <div class="display-inline-block width-200px favorite-post-container">
                <p class="truncate-string"><?php echo $oneComment['comment_text']; ?></p>
            </div>
        <?php
        }
        ?>
        </div>
    </div>
</div>