<div id="main-panel" class="bb">
    <div class="galery-upload m-t-20">
        <h2><?php echo $this->translate->_('Upload pictures'); ?></h2>
        <input type="file" class="upload-change-it m-t-10 float-left" id="fileupload" name="files[]" data-url="<?php echo APP_URL; ?>/galery/upload/galeryID/<?php echo $this->galeryID; ?>" multiple/>
        <a class="float-right green-button back-to-galery" href="<?php echo APP_URL; ?>/galery/index"><?php echo $this->translate->_('Back To Galery'); ?></a>
    </div>
    <div id="progress">
        <div class="bar" style="width: 0%;"></div>
    </div>
    <hr>
    <div class="gallery album">
    <?php
        foreach ($this->images as $oneImage) {
            ?>
            <a title="<?php echo $oneImage->id; ?>" href="<?php echo APP_URL . '/' . Galery::GALERY_IMAGES_FOLDER . '/' . $oneImage->url; ?>" class="main-background-color one-galery-item">
                <div class="remove-galery-item">
                    <i class="fa fa-times modal-open" data-url="/galery/delete-image?imageID=<?php echo $oneImage->id; ?>"></i>
                </div>
                <img src="<?php echo APP_URL . '/' . Galery::GALERY_IMAGES_FOLDER . '/' . $oneImage->url; ?>" >
            </a>
            <?php
        }
    ?>
    </div>
</div>
<div class="galery-overlay">
    <div class="galery-comment-holder">
        <div class="post-footer bb galery-comment">
            <?php echo $this->form; ?>
            <div class="post-comment-list bb">
                <div class="clear"></div>
                <div class="show-more-post-comments">
                    <i class="fa fa-toggle-down"></i>
                    <i class="fa fa-spinner fa-spin display-none"></i>
                </div>    
            </div>
        </div>
    </div>
    <div class="galery-image"></div>
</div>