<div class="submit-modal-template display-none">
    <button type="button" class="btn btn-primary pull-right submit-modal-form green-button">
        <?php echo $this->translate->_('Save changes'); ?>
    </button>
</div>
<div class="delete-modal-template display-none">
    <button type="button" class="btn btn-primary pull-right submit-modal-form red-button">
        <?php echo $this->translate->_('Delete'); ?>
    </button>
</div>