<aside class="chat-sidebar position-fixed main-background-color">
    <div class="chat-search">
        <input class="search-person-chat" type="text" / placeholder="<?php echo $this->translate->_('Type to search friends'); ?>" class="bb">
        <i class="fa fa-search"></i>
        <i class="fa fa-times display-none"></i>
    </div>
    <?php
        foreach ($this->friends as $key => $value) {
            if ($value['id'] != $this->userID) {
        ?>
                <div class="one-chat-person offline" id="<?php echo $value['id']; ?>">
                    <div class="chat-avatar">
                        <img src="<?php echo Utils::generateUrl(array(APP_URL, UserInfo::AVATAR_IMAGES_FOLDER, $value['avatar'])); ?>" />
                    </div>
                    <div class="chat-availability bb"></div>
                        <div class="chat-person-name">
                        <p class="truncate-string"><?php echo Utils::mergeStrings(array($value['first_name'], $value['last_name'])); ?></p>
                    </div>
                </div>
        <?php 
            }
        }
    ?>
</aside>
<?php
