<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content main-background-color">
            <div class="modal-header">
                <div class="modal-header-close"><i class="fa fa-times"></i></div>
                <div class="modal-header-title bb">
                    <p class="truncate-string">This is some very long title of some dialog</p>
                </div>
            </div>
            <div class="modal-body bb">
                <div class="mcl" style="text-align: center;">
                    <i style="font-size: 50px;" class="fa fa-spinner fa-spin"></i>
                </div>
                <div class="mc">
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default cls" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary pull-right submit-modal-form green-button">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->