<!DOCTYPE html>
<html>
    <head>
        <title>Sportalize - Welcome</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->render('includes/css.phtml'); ?>
        <?php echo $this->render('includes/login-css.phtml'); ?>
    </head>
    <body class="main-background-color">
        <?php echo $this->layout()->content; ?>
    </body>
</html>