<!DOCTYPE html>
<html>
    <head>
        <title>Sportalize</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->render('includes/fonts.phtml'); ?>
        <?php echo $this->render('includes/plugins-css.phtml'); ?>
        <?php echo $this->render('includes/css.phtml'); ?>
    </head>
    <body>
        <input type="hidden" value="<?php echo APP_URL; ?>" class="appurl">
        <input type="hidden" value="<?php echo $this->userID; ?>" class="userID">
        <?php
            $session = new Zend_Session_Namespace(Sportalize_Controller_Action::SESSION_NAMESPACE_NOTIFICATION);
            if (!empty($session->notificationStatus)) {
                ?>
                <input type="hidden" value="<?php echo $session->notificationStatus; ?>" class="notification-status">
                <input type="hidden" value="<?php echo $session->notificationMessage; ?>" class="notification-message">
                <?php
                unset($session->notificationStatus);
                unset($session->notificationMessage);
            }
        ?>
        <header class="widget-header-color">
            <nav role="navigation" class="header-holder">
                <div class="h">
                    <ul class="main-link-ul">
                    <?php
                    foreach ($this->links as $oneLink) {
                        ?>
                        <li class="cc main-link-li">
                            <a href="<?php echo $oneLink['url'] ?>"><?php echo $oneLink['title']; ?></a>
                            <?php
                            if (isset($oneLink['sublinks'])) {
                                ?>
                                <ul class="sublink-ul sublink-ul-1">
                                <?php
                                foreach ($oneLink['sublinks'] as $oneSublink) {
                                    ?>
                                    <li class="cc sublink-li-1 bb main-background-color">
                                    <?php $link = $oneSublink['url'] != 'javascript:void(0)' ? APP_URL . $oneSublink['url'] : $oneSublink['url']; ?>
                                        <a href="<?php echo $link; ?>"><?php echo $oneSublink['title']; ?></a>
                                    </li>
                                    <?php
                                }
                                ?>
                                </ul>
                                <?php
                            }
                            ?>
                        </li>
                        <?php
                    }
                    ?>
                    </ul>
                </div>
                <a data-url="/post/new-post" href="javascript:void(0)" class="new-post modal-open" data-template="new-post-template">
                    <?php echo $this->translate->_('New Post'); ?>
                </a>
            </nav>
        </header>
        <?php echo $this->render('includes/chat.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <script src="<?php echo APP_URL; ?>/js/jquery-1.11.2.min.js"></script>
        <?php echo $this->render('includes/plugins-js.phtml'); ?>
        <?php echo $this->render('includes/js.phtml'); ?>
        <?php echo $this->render('includes/modal.phtml'); ?>
    </body>
</html>