<!DOCTYPE html>
<html>
    <head>
        <title>Sportalize</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->render('includes/fonts.phtml'); ?>
        <?php echo $this->render('includes/plugins-css.phtml'); ?>
        <?php echo $this->render('includes/css.phtml'); ?>
    </head>
    <body>
        <input type="hidden" value="<?php echo APP_URL; ?>" class="appurl">
        <input type="hidden" value="<?php echo $this->userID; ?>" class="userID">
        <input type="hidden" value="<?php echo $this->datePickerFormat; ?>" class="datePickerFormat">
        <?php
            $session = new Zend_Session_Namespace(Sportalize_Controller_Action::SESSION_NAMESPACE_NOTIFICATION);
            if (!empty($session->notificationStatus)) {
                ?>
                <input type="hidden" value="<?php echo $session->notificationStatus; ?>" class="notification-status">
                <input type="hidden" value="<?php echo $session->notificationMessage; ?>" class="notification-message">
                <?php
                unset($session->notificationStatus);
                unset($session->notificationMessage);
            }
        ?>
        <header class="widget-header-color">
            <nav role="navigation" class="header-holder">
                <div class="h">
                    <ul class="main-link-ul">
                    <?php
                    foreach ($this->links as $oneLink) {
                        ?>
                        <li class="cc main-link-li">
                        <?php
                            $translatedMenuLinks = MenuLink::getTranslatedMenuTitles();
                            if ($oneLink['title'] == MenuLink::MENU_LINK_MY_POSTS) {
                                $oneLink['url'] = $oneLink['url'] . '?userID=' . $this->userID;
                            }
                            if ($oneLink['title'] == MenuLink::MENU_LINK_NOTIFICATIONS) {
                                $oneLink['sublinks'] = MenuLink::addNotificationsSubmenu($this->notifications);
                            }
                            
                        ?>
                            <a href="<?php echo $oneLink['url'] ?>"><?php echo $translatedMenuLinks[$oneLink['title']]; ?></a>
                            <?php
                            if ($this->user->hasNewNotifications() && $oneLink['title'] == MenuLink::MENU_LINK_NOTIFICATIONS) {
                                ?>
                                <i class="fa fa-exclamation"></i>
                                <?php
                            }
                            if (isset($oneLink['sublinks'])) {
                                ?>
                                <ul class="sublink-ul sublink-ul-1 <?php echo $oneLink['class']?> ">
                                <?php
                                foreach ($oneLink['sublinks'] as $oneSublink) {
                                    echo $this->partial('includes/sublink-1.phtml', array(
                                        'oneSublink' => $oneSublink,
                                        'user'       => $this->user
                                    ));
                                }
                                ?>
                                </ul>
                                <?php
                            }
                            ?>
                        </li>
                        <?php
                    }
                    ?>
                    </ul>
                </div>
                <a data-url="/post/new-post" href="javascript:void(0)" class="new-post modal-open" data-template="new-post-template">
                    <?php echo $this->translate->_('New Post'); ?>
                </a>
            </nav>
        </header>
        <?php echo $this->render('includes/chat.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <script src="<?php echo APP_URL; ?>/js/jquery-1.11.2.min.js"></script>
        <?php echo $this->render('includes/plugins-js.phtml'); ?>
        <?php echo $this->render('includes/js.phtml'); ?>
        <?php echo $this->render('includes/modal.phtml'); ?>
        <?php echo $this->render('includes/buttons.phtml'); ?>
    </body>
</html>