<div class="one-post-comment">
    <div class="post-comment-avatar">
        <a href="<?php echo APP_URL . '/index/profile?userID=' . $this->oneComment['commenter_id']; ?>" >
            <img src="<?php echo APP_URL; ?>/<?php echo UserInfo::AVATAR_IMAGES_FOLDER . '/' . $this->oneComment['avatar']; ?>">
        </a>
    </div>
    <div class="one-post-actions-holder" id="<?php echo $this->oneComment['comment_id']; ?>" >
        <a class="like-or-unlike-comment" <?php echo empty($this->oneComment['user_like']) ? '': 'style="display: none;"'; ?> href="javascript:void(0)">
            <i class="fa fa-thumbs-up"></i>
        </a>
        <a class="like-or-unlike-comment" <?php echo empty($this->oneComment['user_like']) ? 'style="display: none;"': ''; ?> href="javascript:void(0)">
            <i class="fa fa-thumbs-down"></i>
        </a>
        <a class="favorite-or-unfavorite-comment" <?php echo empty($this->oneComment['comment_favorite']) ? '': 'style="display: none;"'; ?> href="javascript:void(0)"><i class="fa fa-heart"></i></a>
        <a class="favorite-or-unfavorite-comment" <?php echo empty($this->oneComment['comment_favorite']) ? 'style="display: none;"': ''; ?> href="javascript:void(0)"><i class="fa fa-heartbeat"></i></a>
        <a data-comment-id=<?php echo $this->oneComment['comment_id']; ?> class="forward-comment post-or-comment-forward pc" href="javascript:void(0)"><i class="fa fa-forward"></i></a>
        <a class="reply-to-comment" href="javascript:void(0)"><i class="fa fa-reply"></i></a>
        <a class="report-comment" href="javascript:void(0)"><i class="fa fa-warning"></i></a>
    </div>
    <div class="one-post-comment-text">
        <p><?php echo $this->oneComment['text']; ?></p>
        <?php
        if (!empty($this->oneComment['reply_to_id'])) {
        ?>
        <a class="reply-to-link" href="<?php echo APP_URL . '/index/profile?userID=' . $this->oneComment['reply_to_id']; ?>">
            <?php echo $this->translate->_('In reply to') . ': ' . $this->oneComment['reply_to_name']; ?>
        </a>
        <?php
        }
        ?>
    </div>
    <div class="post-count-and-date">
        <p class="like-count"><?php echo $this->oneComment['likes'] ? $this->oneComment['likes'] . ' ' . $this->translate->_('Likes') : ''; ?></p>
        <p><?php echo $this->oneComment['forwarded'] ? $this->oneComment['forwarded'] . ' ' . $this->translate->_('Forwards') : '';?></p>
        <p class="pull-right"><?php echo Utils::timestampToLocale($this->oneComment['date']); ?></p>
    </div>
</div>
<?php
