<?php
$object        = $this->object;
$options       = Utils::arrayFetch($this, 'options', array());
$printDelete   = Utils::arrayFetch($options, 'print_delete', false);
$dataUrl       = Utils::arrayFetch($options, 'data-url', false);
$form          = Utils::arrayFetch($this, 'form', false);
$itemDelete    = Utils::arrayFetch($options, 'item-delete-class', false);
$deleteOptions = Utils::arrayFetch($options, 'delete-options', '');

?>
<div class="main-background-color one-personal-settings-section position-relative">
    <h2 class="widget-header-color display-inline-block"><?php echo $this->title; ?></h2>
    <div class="display-inline-block">
    <?php
    if ($form) {
        echo $form;
    }
    ?>
    </div>
    <?php
    if ($printDelete) {
    ?>
    <i data-url="<?php echo $dataUrl; ?>" class="modal-open fa fa-times cursor-pointer remove-friend-list" style="color:red;"></i>
    <?php
    }
    ?>
    <div class="p-10">
    <?php
    $count = 1;
    
    if (!empty($object) && key($object) !== 'options') {
        unset($object['options']);
        foreach ($object as $key => $oneObject) {
            if ($key !== 'options') {
                $urlLogo = $this->personOrPage == 'person' ?
                '/' . UserInfo::AVATAR_IMAGES_FOLDER . '/' . $oneObject['avatar'] :
                '/' . Page::PAGE_IMAGES_FOLDER . '/' . $oneObject['logo'];
                $urlPage = $this->personOrPage == 'person' ?
                '/index/profile?userID=' . $oneObject['id'] :
                '/page/index?pageID=' . $oneObject['id'];
                $name = $this->personOrPage == 'person' ? $oneObject['name'] : $oneObject['title'];
                if ($count == 1) {
                    ?>
                    <div class="one-search-container">
                    <?php
                }
                    ?>
                        <div class="m-b-10 position-relative">
                            <?php
                            if ($itemDelete) {
                            ?>
                            <i <?php echo $deleteOptions; ?> data-id="<?php echo $oneObject['id']; ?>" class="fa fa-times cursor-pointer <?php echo $itemDelete; ?>"></i>
                            <?php
                            }
                            ?>
                            <div class="person-avatar pull-left">
                                <img src="<?php echo APP_URL . $urlLogo ?>">
                            </div>
                            <p class="pull-left m-l-5">
                                <a href="<?php echo APP_URL . $urlPage; ?>">
                                    <?php echo $name; ?>
                                </a>
                            </p>
                            <div class="clear"></div>
                        </div>
                    <?php
                if ($count == 5 || $count == count($object)) {
                    ?>
                    </div>
                    <?php
                    $count = 1;
                } else {
                    $count++;
                }
            }
        }
    } else {
        ?>
        <p><?php echo $this->translate->_('No results found') ?></p>
        <?php
    }
    ?>
    </div>
    <div class="clear"></div>
</div>
<?php
