<?php $object = $this->object; ?>
<div class="main-background-color one-personal-settings-section">
    <h2 class="widget-header-color display-inline-block"><?php echo $this->title; ?></h2>
    <div class="p-10">
    <?php
    $count = 1;
    if (!empty($object)) {
        foreach ($object as $oneObject) {
            $urlLogo = $this->personOrPage == 'person' ?
            '/' . UserInfo::AVATAR_IMAGES_FOLDER . '/' . $oneObject['avatar'] :
            '/' . Page::PAGE_IMAGES_FOLDER . '/' . $oneObject['logo'];
            $urlPage = $this->personOrPage == 'person' ?
            '/index/profile?userID=' . $oneObject['id'] :
            '/page/index?pageID=' . $oneObject['id'];
            $name = $this->personOrPage == 'person' ? $oneObject['name'] : $oneObject['title'];
            if ($count == 1) {
                ?>
                <div class="one-search-container">
                <?php
            }
                ?>
                    <div class="m-b-10">
                        <div class="person-avatar pull-left">
                            <img src="<?php echo APP_URL . $urlLogo ?>">
                        </div>
                        <p class="pull-left m-l-5">
                            <a href="<?php echo APP_URL . $urlPage; ?>">
                                <?php echo $name; ?>
                            </a>
                        </p>
                        <div class="clear"></div>
                    </div>
                <?php
            if ($count == 5 || $count == count($object)) {
                ?>
                </div>
                <?php
                $count = 1;
            } else {
                $count++;
            }
        }
    } else {
        ?>
        <p><?php echo $this->translate->_('No results found') ?></p>
        <?php
    }
    ?>
    </div>
    <div class="clear"></div>
</div>