 <div class="one-post video main-background-color" id="<?php echo $this->onePost['post_id']; ?>">
 <?php //fb($this->onePost); ?>
    <div class="post-header bb widget-header-color">
        <div class="post-header-close">
            <i class="fa fa-thumbs-up like-or-unlike-post" <?php echo empty($this->onePost['post_like']) ? '' : 'style="display:none";' ; ?> ></i>
            <i class="fa fa-thumbs-down like-or-unlike-post" <?php echo empty($this->onePost['post_like']) ? 'style="display:none";' : '' ; ?> ></i>
            <i class="fa fa-heart favorite-or-unfavorite-post" <?php echo empty($this->onePost['post_favorite']) ? '' : 'style="display:none";' ; ?>></i>
            <i class="fa fa-heartbeat favorite-or-unfavorite-post" <?php echo empty($this->onePost['post_favorite']) ? 'style="display:none"' : '' ; ?>></i>
            <?php if (Post::determineIfForwardShouldBeVisible($this->watcher->id, $this->onePost['user_id'], $this->onePost['page_id'])) { ?>
            <i data-post-id="<?php echo $this->onePost['post_id']; ?>" class="fa fa-forward post-or-comment-forward pf"></i>
            <?php } ?>
        </div>
        <div class="post-header-title bb">
            <h2 class="truncate-string"><?php echo $this->onePost['title']; ?></h2>
        </div>
    </div>
    <div class="post-body bb">
    <div>
        <p class="post-details">
            <?php
            $url = !empty($this->onePost['user_id']) ?
             '/index/profile?userID=' . $this->onePost['user_id'] :
             '/page/index?pageID=' . $this->onePost['page_id'];
            ?>
            <span><?php echo $this->translate->_('By'); ?></span>:
            <a href="<?php echo APP_URL . $url; ?>"><?php echo $this->onePost['post_author']; ?></a>
        </p>
        <?php
        if (!empty($this->onePost['original_post_author'])) {
        ?>
        <p class="post-details">
            <?php
            $url = !empty($this->onePost['original_user_id']) ?
             '/index/profile?userID=' . $this->onePost['original_user_id'] :
             '/page/index?pageID=' . $this->onePost['original_page_id'];
            ?>
            <span><?php echo $this->translate->_('Originaly posted by'); ?></span>:
            <a href="<?php echo APP_URL . $url; ?>"><?php echo $this->onePost['original_post_author']; ?></a>
        </p>
        <?php
        }
        ?>
        <p class="post-details">
            <span><?php echo $this->translate->_('Likes'); ?></span>:
            <?php echo Post::getPostLikesCount($this->onePost['post_id']); ?>
        </p>
        <p class="post-details">
            <span><?php echo $this->translate->_('Posted'); ?></span>:
            <?php echo Utils::timestampToLocale($this->onePost['date']); ?>
        </p>
    </div>
    <?php
        if ($this->onePost['type'] == Post::POST_TYPE_VIDEO) {
        ?>
            <iframe src="http://www.youtube.com/embed/<?php echo $this->onePost['video']; ?>"></iframe>
        <?php
        }
        if ($this->onePost['type'] == Post::POST_TYPE_IMAGE) {
            $url = Post::getImageUrl($this->onePost['image']);
        ?>
            <img src="<?php echo $url; ?>">
        <?php
        }
    ?>
        <div class="post-text">
            <p><?php echo $this->onePost['text']; ?></p>
        </div>
    </div>
    <div class="post-footer bb">
        <?php echo $this->form; ?>
        <div class="post-comment-list bb">
            <?php
                $count = 0;
                if (isset($this->onePost['comments'])) {
                    foreach ($this->onePost['comments'] as $oneComment) {
                        echo $this->partial('render/comment.phtml', array('oneComment' => $oneComment, 'translate' => $this->translate));
                        $count++;
                        if ($count == 5 ) {
                            break;
                        }
                    }
                }
            ?>
            <div class="clear"></div>
            <div class="show-more-post-comments">
                <i class="fa fa-toggle-down"></i>
                <i class="fa fa-spinner fa-spin display-none"></i>
            </div>
        </div>
    </div>
</div>
<?php
