<form id="edit-lweb-data">
    <div class="add-list-with-button-settings-panel">
    <?php $decoded = $this->decoded; ?>
        <input type="hidden" value="<?php echo $this->widgetOptionID; ?>" class="widgetOptionID">
        <input type="hidden" value="<?php echo $this->itemID; ?>" class="itemID">
        <div>
            <select class="float-left list-with-button-select">
                <option><?php echo $this->translate->_('Name'); ?></option>
                <?php
                foreach ($this->widgetData as $key => $value) {
                    ?>
                    <option value="<?php echo $value->title; ?>"><?php echo $value->title; ?></option>
                    <?
                }
                ?>
            </select>
            <a class="blue-button add-list-with-button-customize-option" href="javascript:void(0)"><?php echo $this->translate->_('Add'); ?></a>
            <select class="float-left list-with-button-select-where-to">
                <option value="main"><?php echo $this->translate->_('Main'); ?></option>
                <option value="additional"><?php echo $this->translate->_('Additional'); ?></option>
            </select>
            <i class="fa fa-times float-right cursor-pointer close-list-with-button-settings-panel"></i>
            <input type="text" class="add-new-lweb-data" placeholder="<?php echo $this->translate->_('Or enter your custom');?>" />
        </div>
        <hr>
        <div class="list-with-button-settings-main">
            <h1 class="text-align-center"><?php echo $this->translate->_('Main Settings'); ?></h1>
            <?php
            $count   = count($decoded['main']['left']);
            $arr     = array('left', 'right');
            foreach ($arr as $leftOrRight) {
            ?>
                <div class="bb lwbsm-<?php echo $leftOrRight; ?>">
                    <?php
                        $counter    = 0;
                        $firstLabel = 'Name';
                        $firstName  = 'name_123456[]';
                        $firstVal   = '';
                        if ($count) {
                            $firstElem  = reset($decoded['main'][$leftOrRight]);
                            $firstLabel = $firstElem['label'];
                            $firstVal   = $firstElem['value'];
                            $firstName  = key($decoded['main'][$leftOrRight]);
                        }
                    ?>
                    <h2 class="text-align-center"><?php echo $firstVal ? $firstVal : 'Option Name'; ?></h2>
                    <div class="list-with-button-settings-item to-be-removed">
                        <label class="truncate-string"><?php echo $firstLabel; ?></label>
                        <input type="text" class="list-with-button-settings-option-name"
                        value="<?php echo $firstVal; ?>" name="main[<?php echo $firstName; ?>][]">
                    </div>
                    <div class="sortable-initialize insert-here">
                    <?php
                    if ($count > 1) {
                        foreach ($decoded['main'][$leftOrRight] as $key => $element) {
                            if ($key != $firstName) {
                                ?>
                                <div class="list-with-button-settings-item to-be-removed">
                                    <label class="truncate-string"><?php echo $element['label']; ?></label>
                                    <i data-closest="lwbsm-<?php echo $leftOrRight; ?>" data-item="item-56478" class="fa fa-times remove-item float-right m-l-5"></i>
                                    <input type="text" value="<?php echo $element['value']; ?>" name="main[<?php echo $key; ?>][]">
                                </div>
                                <?php
                            }
                        }
                    }
                    ?>
                    </div>
                </div>
            <?php
            }
            ?>
            <div class="clear"></div>
        </div>
        <div class="list-with-button-settings-additional">
            <div style="display:none;" class="to-be-removed"></div>
            <h1 class="text-align-center"><?php echo $this->translate->_('Additional Settings'); ?></h1>
            <div class="bb p-10 sortable-initialize">
            <?php
            if (isset($decoded['additional'])) {
                $count   = count($decoded['additional']);
                if ($count) {
                    foreach ($decoded['additional'] as $key => $value) {
                        ?>
                            <div class="list-with-button-settings-item to-be-removed">
                                <label class="truncate-string"><?php echo $value['label']; ?></label>
                                <i data-closest="list-with-button-settings-additional" class="fa fa-times remove-item float-right m-l-5"></i>
                                <input type="text" name="<?php echo $key; ?>" value="<?php echo $value['value']; ?>">
                            </div>
                        <?php
                    }
                }
            }
            ?>
            </div>
        </div>
        <div>
            <a class="green-button lwb-save"><?php echo $this->translate->_('Save'); ?></a>
        </div>
    </div>
</form>