<div class="new-widget-modal">
    <?php echo $this->form; ?>
</div>
<div class="list-with-edit-button-option-template display-none">
    <div class="modal-element to-be-removed">
        <label class="main-label"><?php echo $this->translate->_('Option Avatars'); ?></label>
        <div class="main-div">
            <input type="hidden" class="h1">
            <input id="" type="file" class="list-option-avatar bb pull-left upload-change-it change_1" />
            <input id="" type="file" class="list-option-avatar bb pull-left upload-change-it m-l-5 change_2" />
            <div class="c1 list-with-button-upload"></div>
            <div class="c2 list-with-button-upload"></div>
            <i data-closest="widget-marker" class="fa fa-times remove-item m-l-5 remove-list-with-button-option" style="display:none;"></i>
            <i data-wiod="new" class="fa fa-cog customize-list-with-edit-button-options"></i>
            <i class="fa fa-spinner fa-spin" style="display:none;"></i>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div class="list-with-edit-button-section-template display-none">
    <div class="one-widget-list-section to-be-removed">
        <div class="modal-element">
            <label class="main-label bold-text" for="list-section-title-1"><?php echo $this->translate->_('List section title'); ?></label>
            <div class="main-div">
                <input type="text" class="widget-list-section-title" name="list-section-title" id="list-section-title-1" />
            </div>
        </div>
        <div class="owls-holder widget-marker sortable-initialize width-95-percent display-inline-block append-into" data-template="list-option-template">
            <div class="modal-element to-be-removed">
                <label class="main-label" ><?php echo $this->translate->_('Option Avatars'); ?></label>
                <div class="main-div">
                    <input type="hidden" class="h1">
                    <input id="" type="file" class="list-option-avatar bb pull-left upload-change-it change_1" />
                    <input id="" type="file" class="list-option-avatar bb pull-left upload-change-it m-l-5 change_2" />
                    <div class="c1 list-with-button-upload"></div>
                    <div class="c2 list-with-button-upload"></div>
                    <i data-closest="widget-marker"class="fa fa-times remove-item m-l-5 remove-list-with-button-option"></i>
                    <i data-wiod="new" class="fa fa-cog customize-list-with-edit-button-options"></i>
                    <i class="fa fa-spinner fa-spin" style="display:none;"></i>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <i class="fa fa-plus m-r-5 add-new-item pull-right" data-html-template="list-with-edit-button-option-template" data-closest="div.one-widget-list-section"></i>
        <i data-closest="div.widget-list-with-edit-button" class="fa fa-times remove-item remove-list-section" style="display: none;"></i>
    </div>
</div>

<div class="list-option-template display-none">
    <div class="modal-element to-be-removed">
        <label class="main-label"><?php echo $this->translate->_('List Option'); ?></label>
        <div class="main-div">
            <input type="text" class="widget-option-and-value bb pull-left t1"  />
            <input type="text" class="widget-option-and-value bb pull-left t2" />
            <i data-closest="widget-marker" class="fa fa-times remove-item m-l-5"></i>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div class="list-section-template display-none">
    <div class="one-widget-list-section to-be-removed">
        <div class="modal-element">
            <label class="main-label bold-text" for="list-section-title-1"><?php echo $this->translate->_('List section title'); ?></label>
            <div class="main-div">
                <input type="text" class="widget-list-section-title" name="list-section-title" id="list-section-title-1" />
            </div>
        </div>
        <div class="modal-element">
            <label class="main-label" for="list-section-title-1"><?php echo $this->translate->_('List section avatar'); ?></label>
            <div class="main-div">
                <input id="" type="file" class="upload-change-it list-option-avatar change_1" />
                <div class="c1 list-with-button-upload">
                </div>
            </div>
        </div>
        <div class="owls-holder widget-marker sortable-initialize width-95-percent display-inline-block append-into" data-template="list-option-template">
            <div class="modal-element to-be-removed">
                <label class="main-label" for="list-section-title-1"><?php echo $this->translate->_('List Option'); ?></label>
                <div class="main-div">
                    <input type="text" class="widget-option-and-value bb pull-left t1" />
                    <input type="text" class="widget-option-and-value bb pull-left t2"/>
                    <i data-closest="widget-marker" class="fa fa-times remove-item m-l-5" style="display:none;"></i>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <i class="fa fa-plus m-r-5 add-new-item" style="vertical-align: top;" data-html-template="list-option-template" data-closest="one-widget-list-section"></i>
        <i data-closest="div.widget-list" class="fa fa-times remove-item remove-list-section" style="display: none;"></i>
    </div>
</div>

<div class="table-option-template display-none">
    <div class="modal-element">
        <label class="main-label cursor-move" for="list-section-title-1"><?php echo $this->translate->_('Option'); ?></label>
        <div class="main-div">
            <input data-id="" type="text"
            class="widget-option-and-value bb pull-left c1" name="" style="width: 85%;" value="" />
            <input type="hidden" name="" value="" class="c2" >
            <i class="fa fa-cog cursor-pointer"></i>
            <i class="fa fa-spin fa-spinner" style="display:none;"></i>
            <i class="fa fa-times remove-item m-l-10" style="font-size: 15px; vertical-align: middle;"></i>
            <div class="clear"></div>
        </div>
    </div>
</div>

<?php
