<div class="form-holder">
    <div class="form-title">
        <h1>Register</h1>
    </div>
    <?php echo $this->form; ?>
    <?php if (isset($_GET['trigger']) && $_GET['trigger'] == 'activate') { ?>
        <p class="login-info">You have registered. To complete your registration, please check your inbox.</p>
    <?php } ?>
    <div class="additional-holder">
        <div>
            <a href="<?php echo APP_URL ?>/login/index/forgot-password">Forgot Password</a>
        </div>
        <div>
            <a href="<?php echo APP_URL ?>/login/index/sign-in">Log In</a>
        </div>
        <div class="clear"></div>
    </div>
</div>