<div class="form-holder">
    <div class="form-title">
        <h1>Register</h1>
    </div>
    <?php echo $this->form; ?>
    <?php if (isset($_GET['action']) && $_GET['action'] == 'activate') { ?>
        <p class="login-info">You have registered. To complete your registration, please check your inbox.</p>
    <?php } ?>
    <div class="additional-holder">
        <div>
            <a href="javascript:void(0)">Forgot Password</a>
        </div>
        <div>
            <a href="<?php echo APP_URL ?>/login/index/sign-up">Log In</a>
        </div>
        <div class="clear"></div>
    </div>
</div>