<div class="form-holder">
    <div class="form-title">
        <h1><?php $this->translate->_('Password reset'); ?></h1>
    </div>
    <?php echo $this->form; ?>
    <?php
        if (isset($this->message)) {
    ?>
        <p class="login-info"><?php echo $this->message; ?></p>
    <?php
        }
    ?>
    <div class="additional-holder">
        <div>
            <a href="<?php echo APP_URL ?>/login/index/register"><?php echo $this->translate->_('Register'); ?></a>
        </div>
        <div>
            <a href="<?php echo APP_URL ?>/login/index/sign-in"><?php echo $this->translate->_('Log In'); ?></a>
        </div>
        <div class="clear"></div>
    </div>
</div>