<div class="form-holder">
    <div class="form-title">
        <h1>Log In</h1>
    </div>
    <?php echo $this->form; ?>
    <?php if (isset($this->message)) { ?>
        <p class="login-info"><?php echo $this->message; ?></p>
    <?php } ?>
    <div class="additional-holder">
        <div>
            <a href="<?php echo APP_URL ?>/login/index/forgot-password">Forgot Password</a>
        </div>
        <div>
            <a href="<?php echo APP_URL ?>/login/index/register">Register</a>
        </div>
        <div class="clear"></div>
    </div>
</div>